version: '3.9'

services:

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend/adllm
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/adllm:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://127.0.0.1:8000

